name: ChessMate Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            echo "🔄 Pulling latest code..."
            cd ~/projects/ChessMate
            git pull origin main
            echo "📦 Installing dependencies..."
            npm install
            echo "⚙️ Building the app..."
            npm run build:server
            echo "🚀 Restarting with PM2..."
            pm2 restart chessmate
